
 

spring:
  application:
    name: airport-services
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      password: 1234
      url: jdbc:mariadb://localhost:3304/airport_app
      username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql=true
#  security:
#    user:
#      name: user
#      password: user


  kafka:
    producer:
      bootstrap-servers=<your-kafka-bootstrap-servers>:
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  level:
    '[org.springframework.security]': DEBUG
     
